# Generated by Django 5.0.1 on 2024-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='initial_price',
        ),
        migrations.AddField(
            model_name='crypto',
            name='price_change_percentage_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='current_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
