# Generated by Django 5.0.1 on 2024-11-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0002_crypto_crypto_id_alter_crypto_market_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='crypto_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
