# Generated by Django 5.0.1 on 2024-12-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0002_remove_crypto_initial_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=20),
        ),
    ]
