# Generated by Django 5.0.1 on 2024-11-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0003_alter_crypto_crypto_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='crypto_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='market_cap',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
