# Generated by Django 5.0.1 on 2024-11-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0004_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='crypto_id',
        ),
        migrations.AddField(
            model_name='crypto',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
