# Generated by Django 5.0.1 on 2024-11-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0005_remove_crypto_crypto_id_crypto_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
