# Generated by Django 5.0.1 on 2024-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0007_alter_crypto_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
