# Generated by Django 5.0.1 on 2024-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0009_portafolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
