# Generated by Django 5.0.1 on 2024-11-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0011_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='initial_price',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venta')], max_length=4),
        ),
    ]
