# Generated by Django 5.0.1 on 2024-11-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0012_rename_date_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Comprar'), ('sell', 'Vender')], max_length=10),
        ),
    ]
